apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart-bot.fullname" . }}
  labels:
    {{- include "helm-chart-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "helm-chart-bot.selectorLabels" . | nindent 4 }}
