image:
  pullPolicy: Always

ingress:
  annotations: {}

replicaCount: 1
resources: {}

postgresql:
  postgresqlUsername: bot
  postgresqlPassword: botreminder
  postgresqlDatabase: bot_db
  fullnameOverride: postgresql
  persistence:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
